stages:
  - dev_layer

merge_be_dev:
  stage: dev_layer
  rules:
    - exists:
        - origin/be
    - changes:
        - origin/be/**
    - when: manual
  script:
    - git config --global user.email "wntjrdbs@gmail.com"
    - git config --global user.name "윤주석"
    - git remote -v
    - git remote remove origin
    - git remote add origin "https://wntjrdbs:3WmDBHzqBCQzswYaBMp5@https://lab.ssafy.com/s10-blockchain-contract-sub2/S10P22A709.git"

    - git fetch 
    - git checkout dev
    - git pull origin dev
    - git merge origin/be --no-edit
    - git push origin dev
  tags: 
    - BE


merge_fe_dev:
  stage: dev_layer
  rules:
    - exists:
        - origin/fe
    - changes:
        - origin/fe/**
    - when: manual
  script:
    - git config --global user.email "wntjrdbs@gmail.com"
    - git config --global user.name "윤주석"
    - git remote -v
    - git remote remove origin
    - git remote add origin "https://wntjrdbs:3WmDBHzqBCQzswYaBMp5@https://lab.ssafy.com/s10-blockchain-contract-sub2/S10P22A709.git"
    
    - git fetch 
    - git checkout dev
    - git pull origin dev
    - git merge origin/fe --no-edit
    - git push origin dev

  tags: 
    - FE
